name: CI Pipeline by Sarthak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Node Dependencies
      run: npm install

    - name: Install Python Dependencies
      run: pip install numpy pandas scikit-learn joblib

    - name: Feature Extraction
      run: node runFeatureExtraction.js loop1.cbl

    - name: Run Prediction
      run: node runPrediction.js

    - name: SLA Check
      id: sla
      run: python sla_check.py

    - name: Send Email on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "❌ SLA Breach Detected"
        body: |
          ALERT 🚨

          SLA validation failed.

          CPU threshold exceeded.

          Please check GitHub Actions logs.

        to: ${{ secrets.EMAIL_USER }}
        from: ${{ secrets.EMAIL_USER }}