name: CI Pipeline by Sarthak

on:
  push:
    branches: [ main ]

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Node Dependencies
      run: npm install

    - name: Install Python Dependencies
      run: pip install numpy pandas scikit-learn joblib

    - name: Feature Extraction
      run: node runFeatureExtraction.js LOOP1.cbl

    - name: Run Prediction
      run: node runPrediction.js

    - name: SLA Check
      run: python sla_check.py

    - name: Create Issue on SLA Failure
      if: ${{ failure() }}
      uses: actions/github-script@v7
      with:
        script: |
          const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "SLA Breach Detected",
            body: "SLA validation failed.\n\nCheck logs:\n" + runUrl,
            labels: ["bug", "SLA", "critical"]
          });